on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
  push:
    branches:
    - main
name: latest
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install pipenv or cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'


      - name: Run get_latest.py
        run: pipenv run python "get_latest.py"

      - name: Pull Remote Changes
        run: git pull
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Chore: latest Update"
          file_pattern: "*.json"
          repository: .
          skip_fetch: false
