on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
  push:
    branches:
    - main
name: latest
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            pip install beautifulsoup4
            pip install pathlib

      - name: Run get_latest.py
        run: |
            python "get_latest.py"
      - name: Pull Remote Changes
        run: git pull
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Chore: mapping Update"
          file_pattern: "*.json"
          repository: .
          skip_fetch: false
