on:
  schedule:
    - cron:  '0 0 * * 0'
  workflow_dispatch:
  push:
    branches:
    - main
name: mapping
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            pip install --upgrade pip
            pip install tqdm
            pip install pathlib
            pip install GitPython

      - name: Run mapper.py
        run: |
            python "mapper.py"
      - name: Pull Remote Changes
        run: git pull
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Chore: mapping Update"
          file_pattern: "mapping.json"
          repository: .
          skip_fetch: false
